- hosts: raspberry
  become: true
  become_user: root
  user: pi
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - alsa-tools
      - sox
      - libsox-fmt-all
  - name: Copy alsa-base.conf
    template:
      src: etc/alsa-base.conf
      dest: /etc/modprobe.d/alsa-base.conf
      owner: root
      group: root
      mode: '0644'
  - name: Enable snd-pcm-oss module
    shell: grep -v snd-pcm-oss /etc/modules > /tmp/modules; echo snd-pcm-oss >> /tmp/modules; mv /tmp/modules /etc/modules
  - name: Reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true
  - name: Wait for rebooting
    local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
    changed_when: false
    become: false
    run_once: true
