- hosts: raspberry
  become: true
  become_user: root
  user: pi
  tasks:
  - name: Cleanup old julius file
    shell: rm -rf /tmp/julius-*
  - name: Download julius file
    shell: cd /tmp; wget https://ja.osdn.net/projects/julius/downloads/66547/julius-4.4.2.tar.gz
  - name: Extract julius file
    shell: cd /tmp; tar xvzf /tmp/julius-4.4.2.tar.gz
  - name: Build julius [1/3]
    shell: cd /tmp/julius-4.4.2; ./configure
  - name: Build julius [2/3]
    shell: cd /tmp/julius-4.4.2; make
  - name: Build julius [3/3]
    shell: cd /tmp/julius-4.4.2; make install
  - name: Remove unnecessary files
    shell: rm -rf /tmp/julius-4.4.2 /tmp/julius-4.4.2.tar.gz
  - name: Enable snd-pcm-oss module
    shell: grep -v snd-pcm-oss /etc/modules > /tmp/modules; echo snd-pcm-oss >> /tmp/modules; mv /tmp/modules /etc/modules


