- hosts: raspberry
  become: true
  become_user: root
  user: pi
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - wireless-tools
      - wpasupplicant
  - name: Reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true
  - name: Wait for rebooting
    local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
    changed_when: false
    become: false
    run_once: true
  - name: Copy wifi config
    template:
      src: etc/wpa_supplicant.conf.j2
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
      owner: root
      group: root
      mode: '0600'
  - name: Make ethernet for direct connection
    template:
      src: etc/dhcpcd.conf
      dest: /etc/dhcpcd.conf
      owner: root
      group: root
      mode: '0664'
  - name: Copy network interfaces config
    template:
      src: etc/interfaces
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
  - name: Reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true
