- hosts: raspberry
  become: true
  become_user: root
  user: pi
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - vim
      - jmtpfs
  - name: Upgrade packages
    shell: apt-get update; apt-get -y upgrade
  - name: Upgrade firmware
    shell: apt-get dist-upgrade
  - name: Reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true
  - name: Wait for rebooting
    local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
    changed_when: false
    become: false
    run_once: true
  - name: Make bin directory
    file: path=/media/android state=directory owner=root group=root mode=0755
