- hosts: raspberry
  become: true
  become_user: root
  user: pi
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - bluealsa
  - name: Copy connect_bt.sh
    template:
      src: ./connect_bt.sh.j2
      dest: /usr/local/bin/connect_bt.sh
      owner: root
      group: root
      mode: '1755'
  - name: Copy .asoundrc
    template:
      src: ./asoundrc.j2
      dest: /home/pi/.asoundrc
      owner: pi
      group: pi
      mode: '0644'
  - name: Connect to bluetooth
    shell: /usr/local/bin/connect_bt.sh
  - name: Reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true
  - name: Wait for rebooting
    local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
    changed_when: false
    become: false
    run_once: true
  - name: Connect to bluetooth
    shell: /usr/local/bin/connect_bt.sh
