- hosts: raspberry
  become: true
  become_user: root
  user: pi
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - gespeaker
      - xsel
  - name: Copy say_something.sh
    template:
      src: say_something.sh
      dest: /usr/local/bin/say_something.sh
      owner: root
      group: root
      mode: '0755'
