name: Pull Request Flow
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build golang sample
        run: |
          ./golang/install_golang.sh
          ./golang/tcp-connection/build.sh
